# This file is the entry point to configure your own process.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    basango_notification_email: '%env(BASANGO_NOTIFICATION_EMAIL)%'

services:
    # default configuration for process in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your process.
        autoconfigure: true # Automatically registers your process as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $crawlingNotificationEmail: '%basango_notification_email%'

    _instanceof:
        Basango\SharedKernel\Application\Messaging\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: 'command.bus' }
        Basango\SharedKernel\Application\Messaging\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: 'query.bus' }
        Basango\SharedKernel\Application\Messaging\MessageHandler:
            tags:
                - { name: messenger.message_handler, bus: 'message.bus' }
        Basango\SharedKernel\Domain\EventListener\EventListener:
            tags:
                - { name: kernel.event_listener }

    Symfony\Bridge\Monolog\Processor\ConsoleCommandProcessor:
        tags:
            - { name: monolog.processor, channel: 'app' }
    Symfony\Bridge\Monolog\Processor\RouteProcessor:
        tags:
            - { name: monolog.processor, channel: 'app' }
    Symfony\Bridge\Monolog\Processor\TokenProcessor:
        tags:
            - { name: monolog.processor, channel: 'app' }
    Basango\SharedKernel\Infrastructure\Framework\Symfony\Logging\TelegramFormatter:
        tags:
            - { name: monolog.formatter }

    # makes classes in src/ available to be used as process
    # this creates a service per class whose id is the fully-qualified class name
    Basango\:
        resource: '../src/'
        exclude:
            - '../src/SharedKernel/Infrastructure/Framework/Symfony/Kernel.php'
            - '../src/**/Domain/Model/Entity/*'
            - '../src/**/Domain/Model/ValueObject/*'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
